export const games = [
  { name: "Geometry Dash", category: "Rhythm", tag: "Timing challenge", featured: true, description: "Fast platform timing game" },
  { name: "Sandboxels", category: "Simulation", tag: "Physics sandbox", featured: true, description: "Pixel sandbox chemistry toy" },

  { name: "2048", category: "Puzzle", tag: "Merge tiles" },
  { name: "Snake", category: "Arcade", tag: "Classic" },
  { name: "Tetris", category: "Puzzle", tag: "Blocks" },
  { name: "Pac-Man", category: "Arcade", tag: "Maze chase" },
  { name: "Dino Run", category: "Runner", tag: "Endless" },
  { name: "Slope", category: "Runner", tag: "Fast roll" },
  { name: "Flappy Bird", category: "Arcade", tag: "Tap to fly" },
  { name: "Cookie Clicker", category: "Idle", tag: "Incremental" },
  { name: "Chess", category: "Board", tag: "Strategy" },
  { name: "Checkers", category: "Board", tag: "Classic" },
  { name: "Minesweeper", category: "Puzzle", tag: "Logic" },
  { name: "Sudoku", category: "Puzzle", tag: "Numbers" },
  { name: "Solitaire", category: "Card", tag: "Single player" },
  { name: "Spider Solitaire", category: "Card", tag: "Classic" },
  { name: "FreeCell", category: "Card", tag: "Planning" },
  { name: "Mahjong", category: "Puzzle", tag: "Tiles" },
  { name: "Wordle", category: "Word", tag: "Daily" },
  { name: "Hangman", category: "Word", tag: "Guessing" },
  { name: "Crossword", category: "Word", tag: "Clues" },
  { name: "Connect Four", category: "Board", tag: "Line up 4" },
  { name: "Tic Tac Toe", category: "Board", tag: "Quick match" },
  { name: "Battleship", category: "Board", tag: "Guessing" },
  { name: "Go Fish", category: "Card", tag: "Family" },
  { name: "Crazy Eights", category: "Card", tag: "Fast card" },
  { name: "Uno", category: "Card", tag: "Party" },
  { name: "Memory Match", category: "Puzzle", tag: "Remember pairs" },
  { name: "Dots and Boxes", category: "Board", tag: "Claim squares" },
  { name: "Mastermind", category: "Puzzle", tag: "Code break" },
  { name: "Jigsaw", category: "Puzzle", tag: "Piece it" },
  { name: "Pinball", category: "Arcade", tag: "Bumpers" },
  { name: "Breakout", category: "Arcade", tag: "Brick breaker" },
  { name: "Asteroids", category: "Arcade", tag: "Space classic" },
  { name: "Space Invaders", category: "Arcade", tag: "Defend earth" },
  { name: "Galaga", category: "Arcade", tag: "Shooter" },
  { name: "Centipede", category: "Arcade", tag: "Retro" },
  { name: "Frogger", category: "Arcade", tag: "Cross the road" },
  { name: "Donkey Kong", category: "Arcade", tag: "Platform" },
  { name: "Mario Runner", category: "Platform", tag: "Jump" },
  { name: "Platform Sprint", category: "Platform", tag: "Speed" },
  { name: "Jetpack Jump", category: "Platform", tag: "Fly high" },
  { name: "Mini Golf", category: "Sports", tag: "Aim and putt" },
  { name: "Basketball Stars", category: "Sports", tag: "Shoot hoops" },
  { name: "Soccer Penalties", category: "Sports", tag: "Penalty kicks" },
  { name: "Racing Drift", category: "Racing", tag: "Drift hard" },
  { name: "Kart Rush", category: "Racing", tag: "Kart racing" },
  { name: "Truck Trial", category: "Racing", tag: "Big wheels" },
  { name: "Bike Stunts", category: "Racing", tag: "Flip tricks" },
  { name: "Moto X", category: "Racing", tag: "Bike racing" },
  { name: "Traffic Escape", category: "Racing", tag: "Weave through" },
  { name: "Temple Run Style", category: "Runner", tag: "Endless run" },
  { name: "Subway Sprint", category: "Runner", tag: "Avoid trains" },
  { name: "Tunnel Rush", category: "Runner", tag: "Tunnel speed" },
  { name: "Friday Night", category: "Rhythm", tag: "Music battle" },
  { name: "Beat Blaster", category: "Rhythm", tag: "Tap to rhythm" },
  { name: "Piano Tiles", category: "Rhythm", tag: "Tap fast" },
  { name: "Tower Defense", category: "Strategy", tag: "Defend lanes" },
  { name: "Kingdom Rush Style", category: "Strategy", tag: "Tactical" },
  { name: "Civilization Lite", category: "Strategy", tag: "Build empire" },
  { name: "Chess AI", category: "Strategy", tag: "Against bot" },
  { name: "Risk Board", category: "Strategy", tag: "World control" },
  { name: "Sudoku Extreme", category: "Puzzle", tag: "Hard mode" },
  { name: "Nonogram", category: "Puzzle", tag: "Picross" },
  { name: "Logic Grid", category: "Puzzle", tag: "Deduction" },
  { name: "Flow Free", category: "Puzzle", tag: "Connect pipes" },
  { name: "2048 Hex", category: "Puzzle", tag: "Tile merge" },
  { name: "Word Search", category: "Word", tag: "Find words" },
  { name: "Typing Test", category: "Skill", tag: "Speed typing" },
  { name: "Aim Trainer", category: "Skill", tag: "Mouse control" },
  { name: "Reaction Time", category: "Skill", tag: "Fast clicks" },
  { name: "Color Switch", category: "Skill", tag: "Timing" },
  { name: "Memory Sequence", category: "Skill", tag: "Repeat pattern" },
  { name: "Math Rush", category: "Education", tag: "Quick maths" },
  { name: "Quiz Master", category: "Education", tag: "Trivia" },
  { name: "Word Builder", category: "Education", tag: "Spelling" },
  { name: "Code Quest", category: "Education", tag: "Logic coding" },
  { name: "Animal Match", category: "Kids", tag: "Matching" },
  { name: "Farm Fun", category: "Kids", tag: "Cute tasks" },
  { name: "Bubble Pop", category: "Arcade", tag: "Pop bubbles" },
  { name: "Balloon Burst", category: "Arcade", tag: "Burst fast" },
  { name: "Paint Splash", category: "Creative", tag: "Colouring" },
  { name: "Draw Lines", category: "Creative", tag: "Physics" },
  { name: "Pixel Art", category: "Creative", tag: "Make art" },
  { name: "Runner X", category: "Runner", tag: "Fast lanes" },
  { name: "Cyber Dash", category: "Runner", tag: "Neon speed" },
  { name: "Jungle Run", category: "Runner", tag: "Obstacle course" },
  { name: "Ice Slide", category: "Runner", tag: "Slippery" },
  { name: "Desert Escape", category: "Runner", tag: "Survive" },
  { name: "Canyon Sprint", category: "Runner", tag: "Leap gaps" },
  { name: "Super Ball", category: "Arcade", tag: "Bounce" },
  { name: "Tiny Tanks", category: "Action", tag: "Tank battle" },
  { name: "Arena Blast", category: "Action", tag: "Fight waves" },
  { name: "Shadow Dodge", category: "Action", tag: "Avoid traps" },
  { name: "Ninja Slice", category: "Action", tag: "Cut fast" },
  { name: "Samurai Dash", category: "Action", tag: "Blade run" },
  { name: "Alien Hunter", category: "Action", tag: "Space fight" },
  { name: "Zombie Wave", category: "Action", tag: "Survival" },
  { name: "Dragon Quest Lite", category: "RPG", tag: "Adventure" },
  { name: "Dungeon Crawl", category: "RPG", tag: "Explore" },
  { name: "Hero Level Up", category: "RPG", tag: "Progression" },
  { name: "Magic Cards", category: "RPG", tag: "Deck battle" },
  { name: "Fishing Frenzy", category: "Relax", tag: "Chill" },
  { name: "Garden Grow", category: "Relax", tag: "Build a garden" },
  { name: "Pet Care", category: "Kids", tag: "Look after pets" },
  { name: "City Builder", category: "Simulation", tag: "Construct" },
  { name: "Airport Tycoon", category: "Simulation", tag: "Manage" },
  { name: "Restaurant Rush", category: "Simulation", tag: "Serve fast" },
  { name: "Hospital Helper", category: "Simulation", tag: "Care tasks" },
  { name: "Delivery Driver", category: "Simulation", tag: "Make deliveries" },
  { name: "Train Manager", category: "Simulation", tag: "Control rails" },
  { name: "Farm Manager", category: "Simulation", tag: "Grow crops" },
  { name: "Space Colony", category: "Simulation", tag: "Build future" },
  { name: "Weather Watch", category: "Simulation", tag: "Forecast" },
  { name: "Ocean Explorer", category: "Adventure", tag: "Discover" },
  { name: "Mountain Trek", category: "Adventure", tag: "Climb" },
  { name: "Cave Explorer", category: "Adventure", tag: "Find treasure" },
  { name: "Lost Island", category: "Adventure", tag: "Survive" },
  { name: "Ancient Ruins", category: "Adventure", tag: "Mystery" },
  { name: "Secret Agent", category: "Adventure", tag: "Spy mission" },
  { name: "Detective Case", category: "Adventure", tag: "Solve clues" },
  { name: "Haunted House", category: "Adventure", tag: "Spooky" },
  { name: "Treasure Hunt", category: "Adventure", tag: "Collect loot" },
  { name: "Robot Factory", category: "Puzzle", tag: "Build bots" },
  { name: "Circuit Crafter", category: "Puzzle", tag: "Wiring" },
  { name: "Bridge Builder", category: "Physics", tag: "Test balance" },
  { name: "Catapult Siege", category: "Physics", tag: "Launch shots" },
  { name: "Stack It", category: "Physics", tag: "Balance blocks" },
  { name: "Roll the Ball", category: "Physics", tag: "Guide marble" },
  { name: "Bottle Flip", category: "Skill", tag: "Timing" },
  { name: "Knife Throw", category: "Skill", tag: "Precision" },
  { name: "Archery Aim", category: "Skill", tag: "Hit target" },
  { name: "Basket Toss", category: "Skill", tag: "Arc shots" },
  { name: "Parking Pro", category: "Skill", tag: "Park neatly" },
  { name: "Snowboard Rush", category: "Sports", tag: "Winter sport" },
  { name: "Skate Park", category: "Sports", tag: "Tricks" },
  { name: "Surf Rider", category: "Sports", tag: "Wave action" },
  { name: "Baseball Hit", category: "Sports", tag: "Bat timing" },
  { name: "Tennis Rally", category: "Sports", tag: "Volley" },
  { name: "Boxing Gym", category: "Sports", tag: "Fight rounds" },
  { name: "Rally Racer", category: "Racing", tag: "Off-road" },
  { name: "Formula Sprint", category: "Racing", tag: "Race cars" },
  { name: "Speedway", category: "Racing", tag: "Track racing" },
  { name: "Night Drive", category: "Racing", tag: "Cruise" },
  { name: "Mini Monsters", category: "RPG", tag: "Collect" },
  { name: "Card Clash", category: "Card", tag: "Battle deck" },
  { name: "Pirate Cove", category: "Adventure", tag: "Sea quest" },
  { name: "Space Miner", category: "Simulation", tag: "Harvest ore" },
  { name: "Ice Cream Shop", category: "Simulation", tag: "Serve orders" },
  { name: "Zoo Keeper", category: "Simulation", tag: "Animal care" },
  { name: "Fashion Studio", category: "Creative", tag: "Dress up" },
  { name: "Music Maker", category: "Creative", tag: "Compose" },
  { name: "Photo Puzzle", category: "Puzzle", tag: "Image logic" },
  { name: "Cloud Jump", category: "Platform", tag: "Hop sky" },
  { name: "Lava Escape", category: "Action", tag: "Run away" },
  { name: "Ice Cave", category: "Adventure", tag: "Explore" },
  { name: "Forest Quest", category: "Adventure", tag: "Journey" },
  { name: "Neon Racer", category: "Racing", tag: "Glowing tracks" },
  { name: "Super Soccer", category: "Sports", tag: "Kick goals" },
  { name: "Volley Smash", category: "Sports", tag: "Smash it" },
  { name: "Bowling Strike", category: "Sports", tag: "Strike zone" },
  { name: "Pool Master", category: "Sports", tag: "Aim shots" },
  { name: "Mahjong Garden", category: "Puzzle", tag: "Relaxing tiles" },
  { name: "Puzzle Box", category: "Puzzle", tag: "Unlock secrets" },
  { name: "Micro Racer", category: "Racing", tag: "Tiny cars" },
  { name: "Street Drift", category: "Racing", tag: "Skid corners" },
  { name: "Monster Truck", category: "Racing", tag: "Big jump" },
  { name: "Jet Ski Race", category: "Racing", tag: "Water speed" },
  { name: "Sky Fighter", category: "Action", tag: "Fly and shoot" },
  { name: "Laser Defender", category: "Action", tag: "Protect base" },
  { name: "Castle Siege", category: "Strategy", tag: "Break walls" },
  { name: "War Tactics", category: "Strategy", tag: "Plan moves" },
  { name: "Puzzle Path", category: "Puzzle", tag: "Solve route" },
  { name: "Gem Collector", category: "Arcade", tag: "Collect gems" },
  { name: "Star Catcher", category: "Arcade", tag: "Grab stars" },
  { name: "Rocket Hop", category: "Arcade", tag: "Launch up" },
  { name: "Neon Maze", category: "Puzzle", tag: "Glow maze" },
  { name: "Turbo Toss", category: "Skill", tag: "Fast throws" },
  { name: "Retro Rally", category: "Racing", tag: "Old-school speed" },
  { name: "Quest Runner", category: "Adventure", tag: "Dash and discover" },
  { name: "Sky Islands", category: "Adventure", tag: "Floating world" },
  { name: "Candy Crush Style", category: "Puzzle", tag: "Match 3" },
  { name: "Block Drop", category: "Puzzle", tag: "Fall fast" },
  { name: "Hexagon Hero", category: "Arcade", tag: "Shape dodge" },
  { name: "Orbit", category: "Arcade", tag: "Circle survive" },
  { name: "Rocket League Style", category: "Sports", tag: "Car soccer" },
  { name: "Dungeon Cards", category: "Card", tag: "Deck adventure" },
  { name: "Battle Grid", category: "Strategy", tag: "Tactical board" },
  { name: "City Escape", category: "Runner", tag: "Fast getaway" },
  { name: "Wild West Run", category: "Runner", tag: "Dusty sprint" },
  { name: "Snow Valley", category: "Runner", tag: "Cold chase" },
  { name: "Tiny Worlds", category: "Creative", tag: "Build worlds" },
  { name: "Brain Teaser", category: "Puzzle", tag: "Think hard" },
  { name: "Hidden Objects", category: "Puzzle", tag: "Find items" },
  { name: "Speed Cards", category: "Card", tag: "Quick play" },
  { name: "Air Hockey", category: "Sports", tag: "Fast puck" },
  { name: "Ping Pong", category: "Sports", tag: "Table tennis" },
  { name: "Dodgeball", category: "Sports", tag: "Throw and dodge" },
  { name: "Street Soccer", category: "Sports", tag: "Urban match" },
  { name: "Robot Wars", category: "Action", tag: "Mech battle" },
  { name: "Starship", category: "Action", tag: "Space combat" },
  { name: "Alien Escape", category: "Adventure", tag: "Run from aliens" }
];
